### ISSUE TITLE
Jira data source authentication

### ISSUE THREAD

**Issue by brmukum** [chaoss/grimoirelab#472] opened 2022-02-23 15:37 UTC
Hey GrimoireLab team! I just one question. To authenticate against a JIRA server to pull data, according to this configs https://chaoss.github.io/grimoirelab-tutorial/docs/data-sources/configurations/#jira, is the backend-user and backend-password the same pair of credentials that could used to log in the JIRA UI ?

**Comment by vchrombie** [comment] 2022-02-23 18:09
> Hey GrimoireLab team! I just one question. To authenticate against a JIRA server to pull data, according to this configs https://chaoss.github.io/grimoirelab-tutorial/docs/data-sources/configurations/#jira, is the backend-user and backend-password the same pair of credentials that could used to log in the JIRA UI ?

Yes, I think you are right. Also, as mentioned in the docs, the credentials are optional (unless it is a private jira instance).

Also, I searched about this. It seems that email and api-token might work as well.
- https://github.com/chaoss/grimoirelab-perceval/issues/752
- https://github.com/chaoss/grimoirelab-perceval/issues/592#issuecomment-559551680

Let us know if it worked. Thanks.

**Comment by vchrombie** [comment] 2022-03-25 08:59
Hi @brmukum, I hope the issue is fixed so I'm closing it right now. Please feel free to open a new one for other doubts.
Thank you.

**Closed by vchrombie** 2022-03-25 08:59 UTC
