### ISSUE TITLE
Strange number in Area of code

### ISSUE THREAD

**Issue by bhack** [chaoss/grimoirelab#426] opened 2021-05-01 22:38 UTC
In the `Most Active Developers` table in the "Area of code" I see very high numbers like "> 2,000,000" added lines for single user.

In the main Git overview instead the top author has "<300,000" added lines that it seems to me more plausible.

Also the top developers names of the two tables mismatch.

**Comment by dicortazar** [comment] 2021-05-04 07:55
Hi @bhack , thanks for your comment!

As a side note to this conversation, I am able to reproduce the issue using the chaoss dashboard (chaoss.biterg.io).

Git index based: https://chaoss.biterg.io/goto/e46f0c5958cc1f6cf7cdd83beb076526
Git areas of code index based: https://chaoss.biterg.io/goto/63ecc51c59498ab771c9da367e184e49

There we can see the list of the contributors with the highest number of added lines and how they differ when using the two different indexes.

**Comment by alpgarcia** [comment] 2021-05-04 15:10
The problem could be the identities management, see:
Valerio Cosentino: https://chaoss.biterg.io/goto/fceb6fa2654783a8b67a39023c14f359
Sean Patrick Goggins: https://chaoss.biterg.io/goto/4e0c3b0131744d0f649712cc8541ec83

They are not correctly merged, so there are commits counted more than once.

Of course, this could be only part of the problem, because one of the profiles associated with Sean seems to have more lines added than those in Git.

**Comment by dicortazar** [comment] 2021-05-04 15:21
Yep, that's the other point, thanks a lot @alpgarcia :).

But as you said, the difference is really high and in the case for instance of Sean, others Sean do not fill that big amount of number of lines.

I think this may be related to how branches are counted or so... but we should have a look at it ....

**Comment by alpgarcia** [comment] 2021-05-05 10:51
The problem comes from duplicated repositories, it seems a repository was renamed but the old data was not removed:
https://chaoss.biterg.io/goto/c6ee85fdc1611ec7de958171e9b870ad

Then the numbers can make no sense at all because the number of contributions will be duplicated in some cases.

On the other hand, identities are not correctly updated, but that extent should not affect the numbers as it would only split one profile into several ones.

**Comment by mafesan** [comment] 2021-05-05 14:33
Just one comment about the example provided by @alpgarcia: the data could be duplicated because there was a renamed project `https://github.com/chaoss/wg-gmd` to `https://github.com/chaoss/wg-evolution`. 

Please @bhack, could you provide any link to the repository or the dashboard you are getting this data from? (in case it is publicly available, of course). Thank you!

**Comment by bhack** [comment] 2021-05-05 14:43
It is not public available but I have the same issue with a single entry starting a Docker container from scratch. 
E.g. I think you can reproduce yourself with https://github.com/tensorflow/tensorflow.

**Comment by sduenas** [comment] 2023-10-27 16:13
Closing this issue due to no activity.

**Closed by sduenas** 2023-10-27 16:13 UTC
