### ISSUE TITLE
Not getting data for github issues and PR's

### ISSUE THREAD

**Issue by harshavardhanc** [chaoss/grimoirelab#242] opened 2019-11-23 17:20 UTC
I'm trying grimoirelab for some open source repositories, I'm getting the data of github commits and repositories. But not getting data for github PR's and issues.
Is there any configuration changes which I need update?

**Comment by valeriocos** [comment] 2019-11-23 17:51
Hi @harshavardhanc , could you share your configuration files? 

Supposing there is no bug ^^, there are two possible explanations that come to my mind:
- Missing `sleep-for-rate` param, which sends the backend to sleep until the API token is exhausted. If this is the case, the collection process will raise an error when the API token gets exhausted. To enable the `sleep-for-rate`, you should modify your github section as follows:
```
[github]
sleep-for-rate = true
```
- Repo(s) with a long list of issues/pull requests. In this case you should pass more tokens to the backend. To do so, you can modify your github section as follows:
```
[github]
api-token = [98c4..., 23a.., as2e..]
```

**Comment by harshavardhanc** [comment] 2019-11-24 15:17
Hi @valeriocos Thanks for the response. Below is my configuration

`
[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
api-token = XXXX
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
`

**Comment by valeriocos** [comment] 2019-11-24 18:30
the github configuration looks ok. Please remember that you can pass a list of tokens to `api-token` if needed. The tokens should be obtained by different github accounts (otherwise all tokens will share the same petitions).

Could you list the github projects you want to analyse?

Thanks

**Comment by harshavardhanc** [comment] 2019-11-25 04:41
@valeriocos All the repositories in our organization account **project-sunbird**.

**Comment by valeriocos** [comment] 2019-11-25 15:59
Sorry for the late reply @harshavardhanc . I'm testing it locally, see below my projects.json and snippet of the cfg file

```
{
    "Sunbird": {
        "github": [
            "https://github.com/project-sunbird/sunbird-analytics",
            "https://github.com/project-sunbird/sunbird-learning-platform",
            "https://github.com/project-sunbird/sunbird-data-pipeline",
            "https://github.com/project-sunbird/sunbird-analytics"
        ],
        "github:prs": [
            "https://github.com/project-sunbird/sunbird-analytics",
            "https://github.com/project-sunbird/sunbird-learning-platform",
            "https://github.com/project-sunbird/sunbird-data-pipeline",
            "https://github.com/project-sunbird/sunbird-analytics"
        ]
    }
}
```

```
[github]
api-token = 9b55...
raw_index = github_sunbird_raw
enriched_index = github_sunbird_enriched
sleep-for-rate = true

[github:prs]
api-token = 9b55...
raw_index = github-prs_sunbird_raw
enriched_index = github-prs_sunbird_enriched
sleep-for-rate = true
category = pull_request
no-archive = true
```

**Comment by valeriocos** [comment] 2019-11-25 17:48
The test has finished and I didn't spot any error, it took around an hour to process the data.
Please find below the indexes generated.

```
green  open searchguard                 Py-HkF1gQwibIOSsxDHEuw 1 0    0   5 33.6kb 33.6kb
yellow open github-prs_sunbird_enriched xHSW4QaITgGix-CWMnVi6A 5 1 1512 910 10.8mb 10.8mb
yellow open github-prs_sunbird_raw      RoV6CRF9TLm4dS0sPcm17w 5 1 1512   0 24.6mb 24.6mb
yellow open github_sunbird_raw          62S7WUsYQDq2leHw4ix9Mw 5 1 1512   0  6.6mb  6.6mb
yellow open github_sunbird_enriched     0nk4CHvzRfCmtmTcNGYVBQ 5 1 1512 739  9.8mb  9.8mb
```

**Comment by harshavardhanc** [comment] 2019-11-25 18:22
Thanks @valeriocos, I was missing **github** and **github:prs** section in project.json. I have updated that and re-ran, but I'm getting _401 Client Error: Unauthorized for url_. I'm passing the correct api token, but still getting this issue and also indices are not getting created. 
Do I need to pass multiple api tokens?

**Comment by valeriocos** [comment] 2019-11-25 18:48
You're welcome @harshavardhanc !

Are you running [grimoirelab](https://github.com/chaoss/grimoirelab) via docker-compose or docker?

**Comment by harshavardhanc** [comment] 2019-11-25 19:01
@valeriocos using docker

**Comment by valeriocos** [comment] 2019-11-25 19:31
Ok, sorry for the imprecision then (I was using the docker-compose) :)

the github token should be defined in the credentials.cfg, as shown below
```
[github]
api-token = 98c46a30df784...

[github:prs]
api-token = 98c46a30df784...
```

**Comment by harshavardhanc** [comment] 2019-11-25 19:48
I have passed the token in credentials.cfg file, after while starting the docker container it is throwing this error. 
`This will usually take a while...
Error while consuming configuration:  ('Missing section param:', 'github:prs', 'raw_index')
`

**Comment by valeriocos** [comment] 2019-11-25 19:56
it seems that `raw_index` isn't defined in `github:prs` section. 
Tomorrow I'll send you a working example with your repos for git and github, using docker.

**Comment by harshavardhanc** [comment] 2019-11-26 03:04
raw_index is defined in the github:prs section, you can see that in the above config. Thanks @valeriocos, will be waiting for your response.

**Comment by valeriocos** [comment] 2019-11-26 19:05
Hi @harshavardhanc , please find below the configurations I used, the docker command and the summary of the results.

**projects.json**
```
{
    "Sunbird": {
        "git": [
            "https://github.com/project-sunbird/sunbird-analytics",
            "https://github.com/project-sunbird/sunbird-learning-platform",
            "https://github.com/project-sunbird/sunbird-data-pipeline",
            "https://github.com/project-sunbird/sunbird-analytics"
        ],
        "github": [
            "https://github.com/project-sunbird/sunbird-analytics",
            "https://github.com/project-sunbird/sunbird-learning-platform",
            "https://github.com/project-sunbird/sunbird-data-pipeline",
            "https://github.com/project-sunbird/sunbird-analytics"
        ],
        "github:prs": [
            "https://github.com/project-sunbird/sunbird-analytics",
            "https://github.com/project-sunbird/sunbird-learning-platform",
            "https://github.com/project-sunbird/sunbird-data-pipeline",
            "https://github.com/project-sunbird/sunbird-analytics"
        ]
    }
}
```

**dashboard.cfg**
```
[general]
# Update incrementally, forever
update = true
# Don't start a new update earlier than (since last update, seconds)
min_update_delay = 300
# Produce debugging data for the logs
debug = true

[es_enrichment]
# Refresh identities and projects for all items after enrichment
autorefresh = true

[sortinghat]
# Run affilation
affiliate = True
# How to match to unify
matching = [email]
# How long to sleep before running again, for identities tasks
sleep_for = 100

[panels]
# Dashboard: default time frame
kibiter_time_from = "now-1y"
# Dashboard: default index pattern
kibiter_default_index = "git"

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
# Names for raw and enriched indexes
raw_index = git_sunbird-raw
enriched_index = git_sunbird
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
# Names for raw and enriched indexes
raw_index = github_sunbird-raw
enriched_index = github_sunbird
no-archive = true
# Sleep it GitHub API rate is exhausted, waited until it is recovered
sleep-for-rate = true

[github:prs]
# Names for raw and enriched indexes
raw_index = prs-github_sunbird-raw
enriched_index = prs-github_sunbird    
no-archive = true
# Sleep it GitHub API rate is exhausted, waited until it is recovered
sleep-for-rate = true
category = pull_request

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_sunbird-raw
out_index = git_aoc_sunbird-enriched

[enrich_onion:git]
in_index = git_sunbird
out_index = git_onion_sunbird-enriched
```
**credentials.cfg**
```
[github]
api-token = a8dccf8...

[github:prs]
api-token = a8dccf8...
```

**docker command**
Run the command in the same folder where the credentials.cfg, dashboard.cfg and projects.json are located.

```
docker run -p 5601:5601 -p 9000:9200 -v $(pwd)/projects.json:/projects.json -v $(pwd)/dashboard.cfg:/dashboard.cfg -v $(pwd)/credentials.cfg:/override.cfg -t grimoirelab/full
```

**results**
The results can be seen using the curl command:
```
slimbook@slimbook-KATANA:~$ curl -XGET http://localhost:9000/_cat/indices
yellow open .kibana                    sabH_BTvQti9SgNL0dezfQ 1 1    172    29   291kb   291kb
yellow open git_sunbird-raw            cIyfMUNhR6ChgW_OgDS0ug 5 1  16919     4    29mb    29mb
yellow open git_sunbird                G9eJpwz_QTSybq64EkdFMQ 5 1  16919     0  48.9mb  48.9mb
yellow open git_aoc_sunbird-enriched   uDt5RmTxTw2S3HxXXcBH5g 5 1 151815 37576   518mb   518mb
yellow open git_onion_sunbird-enriched 37bh2LESQseUKugcc9BwzA 5 1   1744     0 732.3kb 732.3kb
yellow open prs-github_sunbird-raw     bS6F8DFvQ3asJsh1w__28Q 5 1    737     0  11.9mb  11.9mb
yellow open github_sunbird-raw         a6Ph5hHcR-211zvwhpiw8A 5 1   1520     3     5mb     5mb
yellow open github_sunbird             w9Zx6tLfQ3CFuHSKhmIMog 5 1   1520     0   5.2mb   5.2mb
```

You can also inspect the logs, to do so:
```
docker ps --> to know the container ID
docker exec -it <container-ID> bash --> to access the container
sudo apt-get install less --> less must be installed within the container
less /logs/all.log --> to inspect the log
```

Hope this helps, and feel free to close the issue if the problem is solved on your side.

**Comment by harshavardhanc** [comment] 2019-11-27 05:58
Great @valeriocos, It worked perfectly. Thanks a lot.
Is there any documentation page where I can refer for running it in docker or docker-compose?
If any, please provide the link.

**Comment by valeriocos** [comment] 2019-11-27 07:57
You're welcome @harshavardhanc !

Sure, please have a look at:
- https://github.com/chaoss/grimoirelab#using-docker-compose
- https://github.com/chaoss/grimoirelab#using-docker-run
- https://chaoss.github.io/grimoirelab-tutorial/sirmordred/container.html

Let's close the issue, feel free to reopen it if needed, thanks

**Comment by harshavardhanc** [comment] 2019-11-27 08:47
Sure @valeriocos closing the issue.

**Comment by harshavardhanc** [comment] 2019-11-28 09:27
@valeriocos After specifying all the repositories which are there in our organization account, it is throwing 404 error, below is the complete error.

> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/project-sunbird/open-saber-client.git/issues?state=all&sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00&direction=asc&per_page=100
> 2019-11-28 09:25:51,699 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://github.com/project-sunbird/openrap-device-mgmt-plugin.git): 404 Client Error: Not Found for url: https://api.github.com/repos/project-sunbird/openrap-device-mgmt-plugin.git/issues?state=all&sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00&direction=asc&per_page=100
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
>     ocean_backend.feed(**params)
>   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
>     self.feed_items(items)
>   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
>     for item in items:
>   File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 215, in fetch
>     for item in self.fetch_items(category, **kwargs):
>   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 323, in __fetch_pull_requests
>     for raw_pull in raw_pulls:
>   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 691, in pulls
>     for raw_issues in issues_groups:
>   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 836, in fetch_items
>     response = self.fetch(url_next, payload=payload)
>   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 818, in fetch
>     response = super().fetch(url, payload, headers, method, stream, verify)
>   File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
>     response = self._fetch_from_remote(url, payload, headers, method, stream, verify, auth)
>   File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 173, in _fetch_from_remote
>     raise e
>   File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 168, in _fetch_from_remote
>     response.raise_for_status()
>   File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/project-sunbird/openrap-device-mgmt-plugin.git/issues?state=all&sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00&direction=asc&per_page=100

I tried passing mutliple api-tokens as well.

**Comment by valeriocos** [comment] 2019-11-28 10:11
It looks like the github repos in your projects.json end with `.git`, try to remove it (and it should work :)). For instance,
`https://github.com/project-sunbird/openrap-device-mgmt-plugin.git` should be `https://github.com/project-sunbird/openrap-device-mgmt-plugin`

**Comment by harshavardhanc** [comment] 2019-11-28 16:35
Ohh thanks, @valeriocos. It's working. Close it again.

**Comment by harshavardhanc** [comment] 2019-12-10 02:02
@valeriocos I was using same configuration which you have provided, everything was working perfectly but after that, we wanted to move this to a different instance after doing that for PR data we are getting only raw data not enriched data. There are no changes in any configuration.

**Closed** 2019-12-10 03:14 UTC
