### ISSUE TITLE
Sentiment fields not available

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab#324] opened 2020-05-15 15:20 UTC
Per the comment in IRC, I followed the [instructions to add the sentiment analysis](https://github.com/chaoss/grimoirelab/tree/master/third-party#docker-image-cross-nlp-rest-api) to our Github index. 

Everything is running as expected however I do not see any of the fields in our index. When I compare the fields on the Chaoss dashboard to ours,there are several which we are missing.

![screenshot-chaoss biterg io-2020 05 15-15_44_08](https://user-images.githubusercontent.com/2930593/82066884-e7cf4400-96c7-11ea-82c6-9ecc873512d9.png)

![screenshot-dashboard mautic org-2020 05 15-15_44_57](https://user-images.githubusercontent.com/2930593/82066880-e56cea00-96c7-11ea-9c78-33506b30aacb.png)

Would appreciate some advice on how to go about this!

**Comment by valeriocos** [comment] 2020-05-15 16:36
Hi @RCheesley , how are you doing?

Did you try to refresh the index pattern (you can do it in the index patterns page, select the index pattern you want and click on the refresh icon on the right side)?

If you share your setup.cfg and projects.json, I can have a closer look. Thanks

**Comment by RCheesley** [comment] 2020-05-15 17:22
That was not in the instructions, but having just done that it doesn't seem to have made any difference.

Excerpt from setup file
```
[github]
api-token = f3e14ddd0b7225bd9af020ea34253a04fcd00052
raw_index = github_demo_raw
enriched_index = github_demo_enriched
sleep-for-rate = true
no-archive = true
category = issue
studies = [enrich_feelings]

[enrich_feelings]
attributes = [body]
nlp_rest_url = http://localhost:2097
```

**Comment by RCheesley** [comment] 2020-05-15 17:24
Hi this instruction wasn't included, but having just run it, it didn't make any difference.

```
[github]
api-token = xxx
raw_index = github_demo_raw
enriched_index = github_demo_enriched
sleep-for-rate = true
no-archive = true
category = issue
studies = [enrich_feelings]

[enrich_feelings]
attributes = [body]
nlp_rest_url = http://localhost:2097
```

**Comment by valeriocos** [comment] 2020-05-16 11:43
Hi @RCheesley, the problem is that the study `enrich_feelings` isn't supported by  the `github` enricher, only `github2` enricher supports it. This is mainly due to the fact that `github2` processes the comments included within issues and pull requests (generating an enriched document for each comment), while `github` doesn't. The study `enrich_feelings` assigns sentiment and emotion for each comment and issue/pull request body.

I'm not sure if it makes sense to enable this study for the `github` enricher since we will get the "feelings" of the issues/pull requests based on their bodies (ignoring their comments). However, if this can be useful for your use case, I can evaluate how to add this study to the `github` enricher.

I followed the steps [here](https://github.com/chaoss/grimoirelab/tree/master/third-party#docker-image-cross-nlp-rest-api) using the CHAOSS repos and was able to see sentiment/emotion data:
![captura_411](https://user-images.githubusercontent.com/6515067/82118564-7bf8e400-9778-11ea-97c2-7a6aa41e233b.png)

The setup.cfg looks like the one below
```
[panels]
...
github-comments = true

[github2:issue]
api-token = xxx
raw_index = github_chaoss_180322
enriched_index = github2_chaoss_180322_enriched_190819
sleep-for-rate = true
no-archive = true
studies = [enrich_feelings]

[enrich_feelings]
attributes = [body]
nlp_rest_url = http://localhost:2901
```

The projects.json looks like the one below
```
"grimoire": {
   "github2:issue": [
            "https://github.com/chaoss/grimoirelab",
            "https://github.com/chaoss/grimoirelab-bestiary",
            "https://github.com/chaoss/grimoirelab-cereslib",
            "https://github.com/chaoss/grimoirelab-elk",
            "https://github.com/chaoss/grimoirelab-graal",
            "https://github.com/chaoss/grimoirelab-hatstall",
            "https://github.com/chaoss/grimoirelab-kibiter",
            "https://github.com/chaoss/grimoirelab-kidash",
            "https://github.com/chaoss/grimoirelab-kingarthur",
            "https://github.com/chaoss/grimoirelab-manuscripts",
          ....
   ]
...
```

A similar example can be found at https://github.com/chaoss/grimoirelab-sirmordred#github2-

Best,
Valerio

**Comment by valeriocos** [comment] 2020-05-18 06:52
Hi @RCheesley any update on this issue?

**Comment by valeriocos** [comment] 2020-05-19 19:11
I close this issue @RCheesley

**Closed by valeriocos** 2020-05-19 19:11 UTC
