### ISSUE TITLE
Github Repos Panel Not Loading

### ISSUE THREAD

**Issue by alangsto** [chaoss/grimoirelab#201] opened 2019-07-15 15:28 UTC
While running the grimoirelab/full docker image, the GitHub Repositories panel will not load and shows an error message. I've included the image of what the dashboard looks like. I have not changed anything from the original docker image except for my github api key. 

<img width="1238" alt="Screen Shot 2019-07-15 at 11 25 07 AM" src="https://user-images.githubusercontent.com/46360176/61228117-9e9f1400-a6f3-11e9-804f-70c987013c07.png">

**Comment by valeriocos** [comment] 2019-07-15 15:55
Hi @alangsto , the issue is related to the missing index `github_repositories`. Please check your setup.cfg, in the `panels` section you should set `github-repos = false`. On the other hand, if you want github repos stats, please add in the setup.cfg and projects.json something similar to:
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/setup.cfg#L101
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/projects.json#L12

Let me know if this solves your issue, thanks

**Comment by alangsto** [comment] 2019-07-15 20:34
Hi @valeriocos,

This did fix the issue! Is there any other place that this was documented? It might be useful for a new user (like myself) to have this be more permanently documented. 

Thanks for your help!

**Comment by valeriocos** [comment] 2019-07-16 06:32
You're welcome @alangsto . The description of the panel section params is at: https://github.com/chaoss/grimoirelab-sirmordred#panels. If you find it useful, feel free to submit a PR to improve the doc. Thanks!

**Comment by valeriocos** [comment] 2019-07-17 07:56
@alangsto let's close this issue. Feel free to submit a PR to improve the doc, thanks!

**Closed by valeriocos** 2019-07-17 07:56 UTC
