### ISSUE TITLE
Using GrimoireLab to analyze internal projects

### ISSUE THREAD

**Issue by MaineC** [chaoss/grimoirelab#455] opened 2021-10-20 12:32 UTC
I would like to use GrimoireLab to analyze some GitHub projects - however they are private projects in a GitHub cloud account, access only possible with 2FA and SSO.

I managed to access GitHub data by configuring an api token in the github section of the setup.cfg file. 

However I seem to be unable to checkout anything from git (tried to use ssh, but I'd rather not put my private keys into the docker container), also tried to use https but couldn't quite figure out, if and how authentication would work. I found two old issues from years ago https://github.com/chaoss/grimoirelab-sirmordred/issues/165 and https://github.com/chaoss/grimoirelab-perceval/issues/398 - but these issues seem to avoid https in the end.

**Comment by sanacl** [comment] 2021-10-21 20:43
Hi @MaineC ,

in order to allow Perceval to collect the data, the token must be included in the projects.json file. Yep, it is pretty awful.

In the example below, the user `bot` has a valid token `******`
```
{
    "the-group-europe": {
        "git": [
            "https://bot:******@github.com/the-group-europe/guitar.git",
            "https://bot:******@github.com/the-group-europe/drums.git",
            ...
```

**Comment by vchrombie** [comment] 2022-01-06 16:54
Hi @MaineC, thanks for opening the issue and sorry for any inconvenience caused.
Could you solve your problem with [@sanacl's comment](https://github.com/chaoss/grimoirelab/issues/455#issuecomment-948988711)?

Please let us know.

**Comment by vchrombie** [comment] 2022-03-25 08:54
Hi @MaineC, I hope the issue is fixed.
Closing this issue, please feel free to open a new one for any other doubts.

**Closed by vchrombie** 2022-03-25 08:54 UTC
Labels: question
